---
title: "Amount of public schools vs. amount of prisons"
author: "Curtis Everett"
description: "Does ratio between schools and prisons matter?"
output:
  distill::distill_article:
    self_contained: false
---


## Project thoughts

In my final project, I am interested in investigating the possible link between the ratio of schools (specifically public schools) to prisons in a given area, and what affect that might have on the prison rate in that community across different age groups and demographics. My hypothesis is that the higher the school to prison ratio is, the less imprisonment a community will experience, especially in minors. To do this I will look at data sets that show me the amount of schools/ prisons in given areas, demographics of people in those areas, priosn rates over periods of times, etc.

In addition, I am also interested in exploring the link between types of music people listen to and he rates of imprisonment for the given genre of music. I am not completely sure how I want to incorporate this at the moment but very much interested. 




